name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test

  Test_Functions:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Test fonction add
        run: ./src/calculator add 10 5

      - name: Test fonction sub
        run: ./src/calculator sub 10 5

      - name: Test fonction mul
        run: ./src/calculator mul 10 5

      - name: Test fonction div
        run: ./src/calculator div 10 5

      - name: Test fonction carre
        run: ./src/calculator carre 2
