name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd "${{ github.repository }}"
          mkdir build
          cd build
          cmake ..
          make
          make test

  Test_Functions:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          cd "${{ github.repository }}/build"
          ./src/calculator add 10 5

      - name: Test fonction sub
        run: |
          cd "${{ github.repository }}/build"
          ./src/calculator sub 10 5

      - name: Test fonction mul
        run: |
          cd "${{ github.repository }}/build"
          ./src/calculator mul 10 5

      - name: Test fonction div
        run: |
          cd "${{ github.repository }}/build"
          ./src/calculator div 10 5

      - name: Test fonction carre
        run: |
          cd "${{ github.repository }}/build"
          ./src/calculator carre 2
